# Generated by Django 3.2.4 on 2021-07-15 14:30

from django.db import migrations, models
import enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('apellido', models.CharField(max_length=75)),
                ('telefono', models.CharField(max_length=75)),
                ('fecha_nacimiento', models.DateField()),
                ('codigo', models.IntegerField(verbose_name=enum.auto)),
                ('tipo_usuario', models.CharField(choices=[('Planta de Oxigeno', 'Si'), ('story', 'no')], max_length=250)),
            ],
        ),
    ]
