# Generated by Django 3.2.4 on 2021-07-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
