# Generated by Django 3.2.4 on 2021-07-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210715_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='offer',
            new_name='tipo_usuario',
        ),
    ]
