# Generated by Django 3.2.4 on 2021-07-15 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_offer_usuarios_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='apellido',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombre',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
