# Generated by Django 3.2.4 on 2021-07-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210715_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('nombres', models.CharField(max_length=75)),
                ('usuario', models.CharField(max_length=75)),
                ('telefono', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=75)),
                ('ruc', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('nombre_empresa', models.CharField(max_length=75)),
            ],
        ),
    ]
