# Generated by Django 3.2.4 on 2021-07-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210715_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
