# Generated by Django 3.2.4 on 2021-07-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210715_1901'),
    ]

    operations = [
        
    ]
