# Generated by Django 3.2.4 on 2021-07-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_empresa_usuario'),
    ]

    operations = [
    ]
