# Generated by Django 3.2.4 on 2021-07-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_empresa_dniempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(max_length=75),
        ),
    ]
