# Generated by Django 3.2.4 on 2021-07-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210722_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=75)),
                ('usuario', models.CharField(max_length=75)),
                ('telefono', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=75)),
                ('ruc', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('nombre_empresa', models.CharField(max_length=75)),
                ('tipo_usuario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('nombres', models.CharField(max_length=75)),
                ('usuario', models.CharField(max_length=75)),
                ('telefono', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=75)),
                ('tipo_usuario', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
        migrations.DeleteModel(
            name='Oxigenodisponible',
        ),
        migrations.RemoveField(
            model_name='puntosred',
            name='codigopuntored',
        ),
        migrations.DeleteModel(
            name='Reservacion',
        ),
        migrations.DeleteModel(
            name='Saturacion',
        ),
        migrations.DeleteModel(
            name='Tipousuario',
        ),
        migrations.DeleteModel(
            name='Usuarioadministrador',
        ),
        migrations.DeleteModel(
            name='Usuariocliente',
        ),
        migrations.DeleteModel(
            name='Ipress',
        ),
        migrations.DeleteModel(
            name='Puntosred',
        ),
    ]
