# Generated by Django 3.2.4 on 2021-07-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210727_1823'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table='accounts_empresa',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='accounts_usuarios',
        ),
    ]
