# Generated by Django 3.2.4 on 2021-07-28 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210727_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='departamento',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empresa',
            name='categoria',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='institucion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nivel',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_usuario',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterModelTable(
            name='empresa',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
