# Generated by Django 3.2.4 on 2021-07-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210727_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
